---
baseurl: https://tahadz.com/
languageCode: en-us
relativeURLs: true
paginate: 6
title: Great projects for Arabic Language

#services:
#  googleAnalytics:
#    id: G-TX4GN1CNZN

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
defaultContentLanguage: ar

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

taxonomies:
  category: categories
  tag: tags
  language: languages
